### PR TITLE
scikit-build-core v0.10.0

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Requesting a package update (before the autotick bot does so automatically). I have a relatively urgent need for this update to align with PyPI's latest version.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
> I have a relatively urgent need for this update to align with PyPI's latest version.

You have my curiosity? :)

**Comment by bdice** [comment]
> I have a relatively urgent need for this update to align with PyPI's latest version.

We're getting ready to ship a new RAPIDS release. We haven't had bandwidth to keep up with some of the deprecations in scikit-build-core, and 0.10.0 breaks our builds. We would like to update our scikit-build-core pinnings to `>=0.10` and set `minimum-version = "0.10"` rather than have conda builds using 0.9 and pip builds using 0.10.

**Comment by bdice** [comment]
There is a failing test:

```
=================================== FAILURES ===================================
________________________ test_broken_code[BROKEN_CODE] _________________________

broken_define = 'BROKEN_CODE'
capfd = <_pytest.capture.CaptureFixture object at 0x7f8752c692e0>

    @pytest.mark.compile()
    @pytest.mark.configure()
    @pytest.mark.usefixtures("broken_fallback")
    @pytest.mark.parametrize("broken_define", ["BROKEN_CMAKE", "BROKEN_CODE"])
    def test_broken_code(broken_define: str, capfd: pytest.CaptureFixture[str]):
        build_wheel("dist", {f"cmake.define.{broken_define}": "1"})
        wheel = Path("dist") / "broken_fallback-0.0.1-py3-none-any.whl"
        with zipfile.ZipFile(wheel) as f:
            file_names = set(f.namelist())
    
        assert file_names == {
            "broken_fallback-0.0.1.dist-info/RECORD",
            "broken_fallback-0.0.1.dist-info/WHEEL",
            "broken_fallback-0.0.1.dist-info/METADATA",
        }
    
        out, err = capfd.readouterr()
        assert "retrying due to override..." in out
    
        if broken_define == "BROKEN_CMAKE":
            assert "Broken CMake" in err
            assert "CMake Error at CMakeLists.txt" in err
            assert "CMake configuration failed" in out
        else:
>           assert "Broken code" in out
E           assert 'Broken code' in '*** scikit-build-core 0.10.0 using CMake 3.30.2 (wheel)\n*** Configuring CMake...\nloading initial cache file /tmp/tmpg1jwmfr6/build/CMakeInit.txt\n-- The C compiler identification is GNU 12.4.0\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working C compiler: $PREFIX/bin/x86_64-conda-linux-gnu-cc - skipped\n-- Detecting C compile features\n-- Detecting C compile features - done\n-- Found Python: $PREFIX/bin/python3.12 (found version "3.12.4") found components: Interpreter Development.Module\n-- Configuring done (0.4s)\n-- Generating done (0.0s)\n-- Build files have been written to: /tmp/tmpg1jwmfr6/build\n*** Building project with Unix Makefiles...\n[ 50%] Building C object CMakeFiles/example.dir/main.c.o\n\n*** CMake build failed - retrying due to override...\n*** scikit-build-core 0.10.0 (wheel)\n*** Making wheel...\n*** Created broken_fallback-0.0.1-py3-none-any.whl\n'
```

**Comment by henryiii** [comment]
I think the compiler error messages are suppressed? It's supposed to be print this out with `#error`. I'm not too worried about it (otherwise it's behaving correctly), so we can skip it for now, and figure out what conda is setting to cause the compiler error message to be hidden later.

**Comment by henryiii** [comment]
> 0.10.0 breaks our builds

It's not supposed to break any existing builds, care to elaborate?

**Comment by bdice** [comment]
> > 0.10.0 breaks our builds
> 
> It's not supposed to break any existing builds, care to elaborate?

I think we're relying on some aspect of `cmake.minimum-version` behavior that was changed? I don't have a specific build log at this moment. We have tracked some of this in https://github.com/rapidsai/build-planning/issues/58.

**Comment by henryiii** [comment]
Okay, commented there. Nothing should be breaking.

**Pull request merged**
